# camera/base.py
from __future__ import annotations
from typing import Protocol, Optional, Tuple

Frame = Tuple[bytes, int, int, int, int]  # data, width, height, stride, capture_ts_ns

class CameraSource(Protocol):
    def start(self) -> None: ...
    def stop(self) -> None: ...
    def get_latest(self) -> Optional[Frame]: ...
    @property
    def measured_fps(self) -> float: ...
