from __future__ import annotations
from typing import Optional, Protocol
from ..core.types import EnginePoll, Vitals


class EngineBase(Protocol):
    def begin_session(self) -> None: ...
    def start(self) -> None: ...
    def stop(self) -> None: ...
    def submit(self, data, width: int, height: int, stride: int, ts_ns: int) -> None: ...
    def poll(self) -> EnginePoll: ...
    def final_results(self) -> Optional[Vitals]: ...
    def close(self) -> None: ...
